set guioptions-=T
set guioptions-=r
set guioptions-=m
"set guifont=InconsolataLGC\ 14
"set guifont=Input\ Mono\ 16
"set guifont=werfProFont\ 20
"set guifont=terminus\ bold\ 18
"set guifont=ibm\ 3270\ 18
set guifont=sudo\ 20
